use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.mogo.com/NexT/MGPod.git'

target 'MGRxKitchen_Example' do
  pod 'MGRxKitchen', :path => '../'

  target 'MGRxKitchen_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
